---
name: CI

on:
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - master

env:
  # Use Xcode 15.2 or newer to support VisionOS
  DEVELOPER_DIR: /Applications/Xcode_15.2.app

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ['iOS Simulator,name=iPhone 15']
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
  analyze:
    name: Analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: analyze
        run: make analyze
  cocoapods:
    name: CocoaPods
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cocoapods lint
        run: make cocoapods
  carthage:
    name: Carthage
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: carthage
        run: make carthage
  swift-package-manager:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify that PINOperation can be built by SPM
        run: make spm
