apple_resource(
  name = 'TestAppResources',
  files = glob(['PINCache/*.png']),
  dirs = [],
)

apple_bundle(
  name = 'TestApp',
  binary = ':TestAppBinary',
  extension = 'app',
  info_plist = 'PINCache/PINCache-Info.plist',
  tests = [':Tests'],
)

apple_binary(
  name = 'TestAppBinary',
  prefix_header = 'PINCache/PINCache-Prefix.pch',
  headers = glob(['PINCache/*.h']),
  srcs = glob(['PINCache/*.m']),
  deps = [
    ':TestAppResources',
    '//:PINCache',
  ],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
  ],
)

apple_package(
  name = 'TestAppPackage',
  bundle = ':TestApp',
)

apple_test(
  name = 'Tests',
  test_host_app = ':TestApp',
  srcs = glob(['PINCacheTests/*.m']),
  info_plist = 'PINCacheTests/PINCacheTests-Info.plist',
  preprocessor_flags = ['-fobjc-arc'],
  frameworks = [
    '$SDKROOT/System/Library/Frameworks/Foundation.framework',
    '$SDKROOT/System/Library/Frameworks/UIKit.framework',
    '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework',
  ],
)
